### ISSUE TITLE
前后台切换之后，图片消失

### ISSUE THREAD

**Issue by kilik52** [TooBug/wemark#12]
这个问题是在真机上发现的，我后来发现在模拟器上也能重现。100%会重现。步骤如下：

1. 加载一个md文件，里面有图片，如下图：

![2017-06-29 5 17 59](https://user-images.githubusercontent.com/37238/27680712-4a13bd8c-5cef-11e7-8561-93877ef2b0ac.jpg)

2. 点击左侧工具栏的“后台”按钮，模拟小程序进入后台，如下图：

![2017-06-29 5 18 14](https://user-images.githubusercontent.com/37238/27680748-65390a72-5cef-11e7-8a19-3f46c2a6d08f.jpg)

3. 点击“前台”按钮，模拟小程序回到前台，等待1~3秒钟，图片就没了。如下图：

![2017-06-29 5 18 21](https://user-images.githubusercontent.com/37238/27680760-78e0f15c-5cef-11e7-8abe-2ee956a9f9b2.jpg)

我可以确定的是，自己放在其他地方的image是不会出现这个问题的。只有wemark解析的image才会有。

**Comment by kilik52** [comment]
先稍微测试了一下，是.wemark_inline_image里面的height:auto的问题。我在debug里面把height:auto关了图片就又出现了

**Comment by TooBug** [comment]
已知，这个问题的背景是这样的：

小程序刚出现的时候不支持图片自动宽高比，所以在`onload`的时候有一个计算图片长宽比，然后绑定高度的逻辑。

后来微信更新了，支持了图片自动宽高比，所以这个特性就不太必要了。再后来可能微信对同一张图片做了缓存，多次访问时不再触发`onload`事件，所以就有了图上的bug。

我自己在一个产品中把这里改掉了，代码还需要整理一下，尽快发布新版本解决。

**Comment by kilik52** [comment]
辛苦了，期待

**Comment by TooBug** [comment]
推送到develop分支了，可以先试一下？

**Comment by kilik52** [comment]
测过了，bug修复了。另外没有发现什么其他问题。

**Comment by TooBug** [comment]
那就好。另外是否方便告知你的小程序名称或者提供小程序码，打算在README中放一个用户墙。

**Comment by kilik52** [comment]
好呀，小程序正在开发中，还没上线。等上线了提供给你哈。

**Comment by TooBug** [comment]
好的。
