### ISSUE TITLE
作者能否支持下 ```的代码段

### ISSUE THREAD

**Issue by FSilence** [TooBug/wemark#13]
作者能否添加一个 对 ```代码段的支持 例如 
```java
public class Test {
}
```

**Comment by FSilence** [comment]
不好意思 我之前部分用的是<pre></pre>标签，，，看错了。。。

**Comment by TooBug** [comment]
好的。没问题的话我先关闭这个issue了。

**Comment by TooBug** [comment]
另外能否告知小程序的名字或者小程序码之类的信息，我可以加到README使用者列表中。

**Comment by FSilence** [comment]
现在还不太清楚审核过后的名字是什么 不出意外 应该是FSilence的博客。。
