### ISSUE TITLE
小程序怎么读取外部md文件并渲染

### ISSUE THREAD

**Issue by lhz1208** [TooBug/wemark#14]
小程序怎么读取外部md文件并渲染

**Comment by TooBug** [comment]
不支持。这是一个笔记软件，不是一个编辑器，所以理论上是不提供外部文件读写的。目前在桌面端提供了单个md文件的导入导出，小程序无法提供。

**Comment by TooBug** [comment]
小程序目前应该不支持外部文件读写的。如果未来支持的话，可以关注小程序的文档。另外wemark只是一个markdown渲染库，只负责从markdown文本渲染到小程序，markdown文本的来源不是wemark关心的事情。
