### ISSUE TITLE
wemark在线上没有效果

### ISSUE THREAD

**Issue by xiezehao** [TooBug/wemark#16]
我的项目在使用wemark作为markdown的渲染库，明明在微信的编译器上能显示效果，但在手机上体验预览和项目上线却不能显示效果，为什么会这样？请尽快解答，新项目要紧

**Comment by TooBug** [comment]
请上代码，否则无法解答。

**Comment by xiezehao** [comment]
@TooBug 
![10](https://user-images.githubusercontent.com/9320056/29667433-fdd5171c-890e-11e7-8a42-f1e60709e6a1.PNG)
![11](https://user-images.githubusercontent.com/9320056/29667434-fdd8ac60-890e-11e7-8b1a-9adbbbbdf73f.PNG)
![12](https://user-images.githubusercontent.com/9320056/29667436-fde06eaa-890e-11e7-86c5-a3c28eea94f3.PNG)
![13](https://user-images.githubusercontent.com/9320056/29667435-fdda69a6-890e-11e7-8d5b-30fa0d4fd3a3.PNG)

基本上按照你的文档配置

**Comment by TooBug** [comment]
有在data中设置wemark对象吗？麻烦给出可调试的代码，看不出来有什么问题。

**Comment by xiezehao** [comment]
@TooBug 有的wemark对象的，基本上按照你的文档来配置，是不是微信小程序的问题，我改用wxParse也是这种情况

**Comment by TooBug** [comment]
你可以尝试抽取一个最简单的demo试一下，比如新建一个test页面，设为小程序进入的主页面，只做markdown渲染。先排除一下是否有其它的干扰。wemark有好几个线上小程序在用的，目前没有发现有不能渲染的情况。

**Comment by xiezehao** [comment]
@TooBug 谢谢，问题已解决。数据从后台获取，然后在success()中调用wemark.parse(),这样子才显示出来
