### ISSUE TITLE
微信小程序升级1.0之后部分显示不正常

### ISSUE THREAD

**Issue by fredyxu** [TooBug/wemark#17]
之前可以正常显示的图片等内容，在升级之后无法正常显示。是否是需要重新匹配还是使用问题？

**Comment by TooBug** [comment]
请问是微信升级了还是wemark升级了？分别给一下微信的版本和wemark的版本？

wemark 1.2.0去掉了之前手工计算图片高度的方式，因为微信基础库支持了固定宽度图片的显示。如果使用的是wemark 1.2.0以上版本和微信低版本，是可能显示不出来的，如果需要全兼容的话，可以考虑使用1.2.0之前的版本。

**Comment by kilik52** [comment]
我也发现这个问题了。微信小程序开发工具，升级到1.0之后，我这边所有文字内容全部不显示了。我目前调试到的阶段是，文字直接在wxml里面没有显示出来。但还没找到为什么

**Comment by kilik52** [comment]
我先把微信小程序开发工具退回到0.22版本了。一切正常。

**Comment by fredyxu** [comment]
是微信开发工具升级了。我现在使用的开发工具的版本是1.01

**Comment by kilik52** [comment]
结果0.22版本，虽然在开发工具里面显示正常。但是打包之后的体验版，包括上传之后的debug版本，全都不正常。文字一概看不到。

**Comment by kilik52** [comment]
找到原因了。是wemark.wxml里面，wx:if="{{renderBlock.content.push}}"这句话出的问题。

我改成了wx:if="{{renderBlock.content.length}}"，

下面相应地改成了wx:if="{{!renderBlock.content.length}}"

应急措施，没仔细考虑过逻辑，不知道length == 0的时候会有什么影响。不过好像不太可能会出现lenght=0？

anyway，这文件我自己调整过其他东西，就不放PR了。

**Comment by TooBug** [comment]
多谢反馈，我排查一下，这个`.push`是用来判断是否是数组的，我再检查一下。

**Comment by sdlyfjx** [comment]
遇到同样问题，差点崩溃了

**Comment by TooBug** [comment]
@sdlyfjx 你有参考楼上的方法修改吗？是否解决了问题？

已经在README显眼位置加了本issue链接。详细情况稍晚一些查明做修复。感谢几位的反馈。

**Comment by sdlyfjx** [comment]
嗯嗯嗯  参考楼上方法临时解决了。布吉岛会不会有问题

**Comment by Jay-Xio** [comment]
代码片段显示不出来

**Comment by joriewong** [comment]
第一个wx:if="{{renderBlock.content.push}}"替换成wx:if="{{!renderBlock.content.push}}"

**Comment by NoraGithub** [comment]
为什么要这样子判断数组呢？可否直接用 Array.isArray 判断？

**Comment by TooBug** [comment]
@NoraGithub N
小程序的模板支持的表达式是一个受限的空间，并不是完整的JS上下文，`Array.isArray`是不被支持的。（如果现在小程序改了，麻烦告知。）

**Comment by NoraGithub** [comment]
@TooBug  谢谢答复，又学到东西。

**Comment by FantaZZ** [comment]
@TooBug  这个项目还在维护不？  看到好几月没有commit...

**Comment by NoraGithub** [comment]
@FantaZZ  因为能用吧

**Comment by FantaZZ** [comment]
@NoraGithub  这个#17，期待正式修复呀~

**Comment by TooBug** [comment]
@NoraGithub @FantaZZ 还在维护的。不过最近一段时间确实挺忙，加上微信小程序和开发工具后来发生了比较大的变化，暂时抽不出时间来系统地整理和测试。

年后应该会正式发布新的版本。
