### ISSUE TITLE
老师您好，我是SDK.cn编辑yuyang

### ISSUE THREAD

**Issue by yuyang2016** [TooBug/wemark#18]
请问可以转载您博客【译】澄清对AMP的十个误解 这篇文章到我们网站吗[SDK.cn](https://sdk.cn ) 会注明来源，作者及出处，谢谢您！

**Comment by TooBug** [comment]
加上出处链接的话，可以的。另外下次这种跟 wemark 无关的事情请直接邮件联系，我博客上都有联系方式，谢谢合作。
