### ISSUE TITLE
为什么wxml报错

### ISSUE THREAD

**Issue by mengzhihoing** [TooBug/wemark#2]
在wxml里面

的tempalte  data="{{...wemark}}"这里...报错

结果编译的时候报错：VM1646:2 ./pages/index/index.wxml
 Bad attr 'data' with message
  1 | <import src="../../wemark/wemark.wxml"/>
> 2 | 

工程文件最好包含完整demo

**Comment by mengzhihoing** [comment]
@TooBug 好吧，是你readme里面的template这个词写错了。。。。我复制进来的。

**Comment by TooBug** [comment]
多谢指出，已修正。
