### ISSUE TITLE
开启ES6->ES5出现异常

### ISSUE THREAD

**Issue by FantaZZ** [TooBug/wemark#20]
[我在开发者社区提问的帖子，各种版本系统信息都在里面](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=743052448&docid=000c8683684730ac70468afd05c800)

不过对显示没有影响

**Comment by TooBug** [comment]
如何确认是remark的问题的？我看了一下这个错误，remark根本没有用到ES6的语法，模板字符串也没有用到。方括号的使用也没有问题。

是否可以简化一下页面的代码，给出一些详细的可重现代码？

**Comment by FantaZZ** [comment]
@TooBug 
这个确实是的，  我把remark的包移除了就没有了~

**Comment by FantaZZ** [comment]
微信的异常信息提示太不完整了，实在没法定位了~

**Comment by TooBug** [comment]
可否提供能够重现的代码？我排查一下。

**Comment by FantaZZ** [comment]
@TooBug 
尴尬， 异常复现不了了， 可能确实是我代码的问题。  我先close了，  要是以后发现在开一个吧
