### ISSUE TITLE
mpvue中能正常使用吗

### ISSUE THREAD

**Issue by flytam** [TooBug/wemark#23]
你好，请问mpvue中使用也是类似配置吗？似乎有点问题

**Comment by TooBug** [comment]
不太清楚mpvue的情况。欢迎提供更具体的环境、使用方式和报错信息。

**Comment by 673800357** [comment]
@TooBug 应该是原生小程序的wxml写法和vue里面有的不兼容，我尝试根据你的库看看能不能封装个mpvue的版本出来

**Comment by 673800357** [comment]
@TooBug [链接](https://github.com/673800357/mpvue-wemark)。这是我这边对你的库适配mpvue做的npm包，主要做了几步：1、把remarkable.js重新打包成ES版本，mpvue默认脚手架是wepack2不支持es commonjs混用 2、把wxml和小程序js层不兼容vue的写法兼容了下。我自己试了下基本可用。

**Comment by TooBug** [comment]
收到，辛苦！

我晚点研究一下，还没有用mpvue写过小程序。issue先保持open，回头我再把mpvue的支持集成过来。

**Comment by TooBug** [comment]
2.0做成了自定义组件，经测试可以在mpvue中使用。
