### ISSUE TITLE
怎么运行demo呢

### ISSUE THREAD

**Issue by jj89757hhb** [TooBug/wemark#24]

**Comment by TooBug** [comment]
文档应该写得比较清楚的。如果没做过小程序的话建议先看小程序文档，学会基本的开发、预览、调试后再使用wemark。如果有具体问题可以再回复。

**Comment by jj89757hhb** [comment]
我肯定打开了  打不开才说的呢

**Comment by TooBug** [comment]
麻烦描述具体问题，否则没有办法帮到你的。
