### ISSUE TITLE
请问能否支持代码高亮？

### ISSUE THREAD

**Issue by herock** [TooBug/wemark#25]
目前渲染的代码段格式没有问题，但不支持代码高亮。非常需要这个功能，请问是否有计划支持？

**Comment by TooBug** [comment]
原理上可行，但是开发工作量会比较多，而且有点担心性能问题，故目前没做实现。

暂时没有明确的支持计划，不排除后续支持的可能。也欢迎自行fork实现后PR。

**Comment by herock** [comment]
好的，谢谢回复。
