### ISSUE TITLE
能否支持 空格+空格+回车换行

### ISSUE THREAD

**Issue by kongzong** [TooBug/wemark#29]
貌似现在只处理了两个回车形成一个段落 `<p>`，但是好像没有处理空格+空格+回车换行  `<br>` 的情况，能否支持？感谢。

**Comment by kongzong** [comment]
在children遍历的时候加了一个判断，暂时解决问题，大意就是碰到软硬回车统一输出`<text>\n<text`
`else if(['softbreak', 'hardbreak'].indexOf(token.type) > -1){
                    ret.push({
                        type: 'text',
                        content: '\n'
                    });
                    env = '';
                }`

尚不知有何不良反应

**Comment by TooBug** [comment]
据我的了解，markdown在渲染时其实并没有软换行一说。两个换行是分段，一个换行只是源码换行，在渲染时并不做什么特殊处理。

当然，因为很难跟不懂markdown的用户解释为什么两次回车才会换行，有很多编辑器对单个回车做了处理，也视为分段依据。但考虑到这个库还是想尽量提供标准化的渲染方案，所以没有特殊处理。如果有需求可以考虑在源码解析前先自行做预处理，将一个换行换成两个换行。

如果这里有其它可供参考的规范，欢迎提供讨论。

**Comment by kongzong** [comment]
我也是刚做一个项目才开始了解的markdown，在markdown一次换行确实不会有实际的换行，但是一般用两个空格加一次换行 会形成实际的换行，跟分段不同，渲染时不会多出一个空行的间距。    
在这个remarkable的demo里可以看到效果：http://jonschlinkert.github.io/remarkable/demo/ 

再次感谢这个库，容易使用，而且性能好。

**Comment by TooBug** [comment]
看到。我会再评估一下。有进一步结论这里回复。

**Comment by TooBug** [comment]
可以支持。2.0会发布这个特性。

**Comment by Flcwl** [comment]
需要手动处理提交的markdown字符串 空格回车符吗？我这里测试 markdown 回车换行转为了 `rnrn`。

**Comment by TooBug** [comment]
@Flcwl 请另开issue详细说明。
