### ISSUE TITLE
使用制表符标识代码段的问题

### ISSUE THREAD

**Issue by kapeter** [TooBug/wemark#31]
问题：
我用的markdown语法中是用制表符来标识代码段，wemark解析不了。

解决方案：
将blockToken.type === 'fence' 改为 blockToken.type === 'code'就好了

**Comment by TooBug** [comment]
既然有解决方案了，帮忙提一个Pull Request？

**Comment by kapeter** [comment]
Pull Request已提交。 #35

**Comment by TooBug** [comment]
close via #35
