### ISSUE TITLE
wemark的taro适配版本

### ISSUE THREAD

**Issue by kapeter** [TooBug/wemark#36]
我用taro框架开发小程序，所以做了一个适配版本。链接：[taro-wemark](https://github.com/kapeter/taro-wemark)

目前，taro框架还不支持第三方组件编译，所以现在是手动引入，后期会改成npm引入。

taro框架：[https://github.com/NervJS/taro](https://github.com/NervJS/taro)

**Comment by TooBug** [comment]
收到。晚点我加到README中！

**Comment by TooBug** [comment]
试验失败，不知道在taro中如何引入小程序自定义组件。https://github.com/NervJS/taro/issues/288

**Comment by kapeter** [comment]
所以我用taro的语法改写wemark

**Comment by TooBug** [comment]
嗯。我问了官方，说还不支持。这个issue先不关，2.0中我放个说明和链接到你的版本。

**Comment by Songkeys** [comment]
Taro v1.0.0-beta.6 支持直接引入第三方组件了：<https://nervjs.github.io/taro/wx-third-party.html>

**Comment by TooBug** [comment]
@Songkeys 我晚点测试下看看，感谢。

**Comment by Songkeys** [comment]
@TooBug 
我已经在项目中集成成功了。使用体验很方便，不需要改动第三方组件的代码。
但是现在 Taro v1.0.0-beta.6 的监听编译还有一点问题。`prism.wxss` 这个文件是单独的 `wxss` 后缀，没有被考虑编译进 `dist` 目录。已经反馈这个 bug 了，等修复之后我会在这个 issue 及时反馈的。

**Comment by TooBug** [comment]
@Songkeys 谢谢！

**Comment by Songkeys** [comment]
Taro 已经支持[使用微信小程序的第三方组件](https://nervjs.github.io/taro/docs/wx-third-party.html)。

在 `src` 下引入 `wemark` 目录后，在页面或者组件里通过配置 `usingComponents` 指定需要引用的第三方组件即可：

```jsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Comp extends Component {
	config = {
		usingComponents: {
			wemark: '../static/wemark/wemark'
		}
	}

    state = {
		md: '# heading'
    }

	render() {
		return (
			<View>
				<wemark md={this.state.md} link highlight type="wemark" />
			</View>
        )
	}
}
```

**Comment by TooBug** [comment]
感谢，回头我再整理下demo一起放上来。

**Comment by joepeak** [comment]
不行呀。

`import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.css'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '区小白每日一问',
    usingComponents: {
      wemark: '../../wemark/wemark'
    }
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  state = {
    md: '#  P2P建立流程'
  }

  render () {
    return (
      <View className='index'>
        <View>
          <Text>问：</Text><Text>什么是区块链</Text>
        </View>
        <View>
          <wemark md={this.state.md} link highlight type="wemark" />
        </View>
      </View>
    )
  }
}`

编译是OK的，没渲染出来

**Comment by joepeak** [comment]
不行的，代码如下：
````
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.css'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '区小白每日一问',
    usingComponents: {
      wemark: '../../wemark/wemark'
    }
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  state = {
    md: '#  P2P建立流程'
  }

  render () {
    return (
      <View className='index'>
        <View>
          <Text>问：</Text><Text>什么是区块链</Text>
        </View>
        <View>
          <wemark md={this.state.md} link highlight type="wemark" />
        </View>
      </View>
    )
  }
}
````

编译是OK的，但没有效果

**Comment by NeroCho** [comment]
同上+1

**Comment by Songkeys** [comment]
@joepeak @NeroCho 
可能编译还是漏了文件，暂时试一下在配置里配置 copy：

```js
  copy: {
    patterns: [
      {
        from: 'src/components/wemark', // wemark 所在位置
        to: 'dist/components/wemark',
      },
    ],
  },
```

详见：https://nervjs.github.io/taro/docs/config-detail.html#copy

**Comment by NeroCho** [comment]
> @joepeak @NeroCho
> 可能编译还是漏了文件，暂时试一下在配置里配置 copy：
> 
> ```js
>   copy: {
>     patterns: [
>       {
>         from: 'src/components/wemark', // wemark 所在位置
>         to: 'dist/components/wemark',
>       },
>     ],
>   },
> ```
> 
> 详见：https://nervjs.github.io/taro/docs/config-detail.html#copy

感谢，已解决

**Comment by DiamondYuan** [comment]
试了一下，没有报错，但是没有任何显示

**Comment by Songkeys** [comment]
@DiamondYuan 
检查一下 dist 文件夹里的 wemark 文件是否齐全。如果不是，按照上面 copy 配置。
文件如果都被编译进去的话，应该是没有问题的。

**Comment by hyacinthus** [comment]
我追踪了一下，是这个版本的remarkable出了问题。
我把它换成最新的版本就好了。

**Comment by Songkeys** [comment]
如果文件都编译了，但是还是渲染不出来，按照 @hyacinthus 说的，确实是 remarkable 的问题。
看了一下 dist 里编译出来的问题，真正的原因貌似是新版 Taro 即使有 copy 配置，也会在 copy 之后编译文件，导致 remarkable.js 这个文件又被编译了一次，而编译结果貌似有点问题。

目前的暂时做法是再在配置里面加上 remarkable 的排除：
```json
  weapp: {
    compile: {
      exclude: [
        'src/components/third-party/wemark/remarkable.js'
      ]
    }
  },
```

确实有点绕，我会让官方人员帮忙看下的……

**Comment by TooBug** [comment]
@hyacinthus 请问最新的remarkable版本是多少？remarkable的Github仓库的dist目录中仍然是1.6.0的版本。

**Comment by TooBug** [comment]
@Songkeys 请问这个问题有改观吗？编译的问题是因为UMD格式导致的还是什么其他原因？

**Comment by Songkeys** [comment]
@TooBug 

仍没有改观。

Taro （目前 v1.2.12）编译的问题有两个：
1. 集成小程序原生组件时，会漏编译仅在 `wxss` 中引用的 `wxss` 文件。本项目中漏编译了 `prism.wxss`。所以需要 `copy` 配置把所有文件在编译时全部拷贝过去。（参考：https://nervjs.github.io/taro/docs/config-detail.html#copy）
2. 在编译压缩过的 js 文件时，会再次经过一次编译导致出错，且无视 `copy` 配置。本项目中是 `remarkable` 文件编译出错。所以需要 `exclude` 配置把压缩的 js 文件排除。（参考：https://nervjs.github.io/taro/docs/config-detail.html#weappcompileexclude）

总结，对于本项目（wemark）来说，完整的解决配置示例如下：

```js
  copy: {
    patterns: [
      {
        from: 'src/components/wemark',
        to: 'dist/components/wemark',
      },
    ],
    options: {},
  },
  weapp: {
    compile: {
      exclude: [
        'src/components/wemark/remarkable.js',
      ]
    }
  },
```

---

之后，通过上面的配置，可以将 wemark 集成在 Taro 中。使用方式是：

在 `src` 下引入 `wemark` 目录后，在页面或者组件里通过配置 `usingComponents` 指定需要引用的第三方组件即可：

```js-jsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Comp extends Component {
	config = {
		usingComponents: {
			wemark: '../components/wemark/wemark'
		}
	}

    state = {
		md: '# heading'
    }

	render() {
		return (
			<View>
				<wemark md={this.state.md} link highlight type="wemark" />
			</View>
        )
	}
}
```

参考：[使用微信小程序的第三方组件](https://nervjs.github.io/taro/docs/wx-third-party.html)

**Comment by TooBug** [comment]
@Songkeys 明白，感谢详细指导。我再确认一下remakeable的版本问题。近期打算发布2.0正式版了。

**Comment by Songkeys** [comment]
@TooBug 
👍 应该和 remarkable 版本没有关系，上面提到真正问题是 Taro 的二次编译。

**Comment by TooBug** [comment]
好的。谢谢！

**Comment by guozimo** [comment]
想问下为什么taro 第一次进入的时候 会把markdown 渲染 之后就出现空白 再也不会渲染了 这个bug 谁来解决一下呢 taro使用者反馈最新消息 看到请加微信 gwd1991 群里都是taro  和wemark的学习开发者 谢谢

**Comment by TooBug** [comment]
@guozimo 请另开issue，另外附上详细的使用方式说明以便复现。

**Comment by guozimo** [comment]
已经创建issue 希望您可以重视一下 加我微信 详细内容说明  谢谢我希望可以和taro-mark的作者直接联系 谢谢您 @kapeter @TooBug @Songkeys @joepeak @NeroCho  微信号：gwd1991 紧急 希望可以理解 谢谢 加我一下 紧急求助 谢谢 生态圈需要完善和扩展 谢谢您

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
// 引入组件
import Taro, { Component } from '@tarojs/taro'
import BdMark from '../../components/wemark'
import { View } from '@tarojs/components'

export default class Index extends Component{

  constructor() {
    super();
    this.state = {
      content: '## hello, world'
    };

  }

  render () {
    return (
      // md为markdown内容
      <View>
      <BdMark md={this.state.content}></BdMark>
      </View>
  )
  }
}

**Comment by guozimo** [comment]
parse(md, options) {
跟踪代码到这里 返回的tokens 是一个空数组 就已经错了
    if(!options) options = {};
    if(!options.name) options.name = 'wemark';
    console.log('parser=====',parser)
    var tokens = parser.parse(md, {});
    console.log('进入函数mdtokens====',tokens)
    // markdwon渲染列表
    var renderList = [];
    // 图片高度数组
    var imageHeight = {};
    // 返回的数据
    var ret = {
      renderList: renderList,
      imageHeight: imageHeight
    };

    var env = [];
    // 记录当前list深度
    var listLevel = 0;
    // 记录第N级ol的顺序
    var orderNum = [0, 0];
    var tmp;

    // 获取inline内容
    var getInlineContent = function(inlineToken){
      var ret = [];
      var env;

      if(inlineToken.type === 'htmlblock'){
        // 匹配video
        // 兼容video[src]和video > source[src]
        var videoRegExp = /<video.*?src\s*=\s*['"]*([^\s^'^"]+).*?(poster\s*=\s*['"]*([^\s^'^"]+).*?)?(?:\/\s*\>|<\/video\>)/g;

        var match;
        var html = inlineToken.content.replace(/\n/g, '');
        while(match = videoRegExp.exec(html)){
          if(match[1]){
            var retParam = {
              type: 'video',
              src: match[1]
            };

            if(match[3]) {
              retParam.poster = match[3];
            }

            ret.push(retParam);
          }
        }
      }else{
        inlineToken.children && inlineToken.children.forEach(function(token, index){
          if(['text', 'code'].indexOf(token.type) > -1){
            ret.push({
              type: env || token.type,
              content: token.content
            });
            env = '';
          }else if(token.type === 'del_open'){
            env = 'deleted';
          }else if(token.type === 'strong_open'){
            env = 'strong';
          }else if(token.type === 'em_open'){
            env = 'em';
          }else if(token.type === 'image'){
            ret.push({
              type: token.type,
              src: token.src
            });
          }
        });
      }

      return ret;
    };

    var getBlockContent = function(blockToken, index){
      if(blockToken.type === 'htmlblock'){
        return getInlineContent(blockToken);
      }else if(blockToken.type === 'heading_open'){
        return {
          type: 'h' + blockToken.hLevel,
          content: getInlineContent(tokens[index+1])
        };
      }else if(blockToken.type === 'paragraph_open'){
        var type = 'p';
        var prefix = '';
        if(env.length){
          prefix = env.join('_') + '_';
        }

        var content = getInlineContent(tokens[index+1]);

        // 处理ol前的数字
        if(env[env.length - 1] === 'li' && env[env.length - 2] === 'ol'){
          content.unshift({
            type:'text',
            content:orderNum[listLevel - 1] + '. '
          });
        }

        return {
          type: prefix + 'p',
          content: content
        };
      }else if(blockToken.type === 'fence'){
        return {
          type: 'code',
          content: blockToken.content
        };
      }else if(blockToken.type === 'code'){
        return {
          type: 'code',
          content: blockToken.content
        };
      }else if(blockToken.type === 'bullet_list_open'){
        env.push('ul');
        listLevel++;
      }else if(blockToken.type === 'ordered_list_open'){
        env.push('ol');
        listLevel++;
      }else if(blockToken.type === 'list_item_open'){
        env.push('li');
        if(env[env.length - 2] === 'ol' ){
          orderNum[listLevel - 1]++;
        }
      }else if(blockToken.type === 'list_item_close'){
        env.pop();
      }else if(blockToken.type === 'bullet_list_close'){
        env.pop();
        listLevel--;
      }else if(blockToken.type === 'ordered_list_close'){
        env.pop();
        listLevel--;
        orderNum[listLevel] = 0;
      }else if(blockToken.type === 'blockquote_open'){
        env.push('blockquote');
      }else if(blockToken.type === 'blockquote_close'){
        env.pop();
      }else if(blockToken.type === 'tr_open'){
        tmp = {
          type: 'table_tr',
          content:[]
        };
        return tmp;
      }else if(blockToken.type === 'th_open'){
        tmp.content.push({
          type: 'table_th',
          content: getInlineContent(tokens[index+1]).map(function(inline){return inline.content;}).join('')
        });
      }else if(blockToken.type === 'td_open'){
        tmp.content.push({
          type: 'table_td',
          content: getInlineContent(tokens[index+1]).map(function(inline){return inline.content;}).join('')
        });
      }
    };

    tokens.forEach(function(token, index){
      var blockContent = getBlockContent(token, index);
      if(!blockContent) return;
      if(!Array.isArray(blockContent)){
        blockContent = [blockContent];
      }
      blockContent.forEach(function(block){
        if(Array.isArray(block.content)){
          block.isArray = true;
        }else{
          block.isArray = false;
        }
        renderList.push(block);
      });
    });

    var obj = {};
    obj[options.name] = ret;

    return renderList;
  }

**Comment by guozimo** [comment]
parse(md, options) {

    if(!options) options = {};
    if(!options.name) options.name = 'wemark';
    console.log('parser=====',parser)
    var tokens = parser.parse(md, {});
    console.log('进入函数mdtokens====',tokens)
空数组返回 错误的
    // markdwon渲染列表
    var renderList = [];
    // 图片高度数组
    var imageHeight = {};
    // 返回的数据
    var ret = {
      renderList: renderList,
      imageHeight: imageHeight
    };

    var env = [];
    // 记录当前list深度
    var listLevel = 0;
    // 记录第N级ol的顺序
    var orderNum = [0, 0];
    var tmp;

    // 获取inline内容
    var getInlineContent = function(inlineToken){
      var ret = [];
      var env;

      if(inlineToken.type === 'htmlblock'){
        // 匹配video
        // 兼容video[src]和video > source[src]
        var videoRegExp = /<video.*?src\s*=\s*['"]*([^\s^'^"]+).*?(poster\s*=\s*['"]*([^\s^'^"]+).*?)?(?:\/\s*\>|<\/video\>)/g;

        var match;
        var html = inlineToken.content.replace(/\n/g, '');
        while(match = videoRegExp.exec(html)){
          if(match[1]){
            var retParam = {
              type: 'video',
              src: match[1]
            };

            if(match[3]) {
              retParam.poster = match[3];
            }

            ret.push(retParam);
          }
        }
      }else{
        inlineToken.children && inlineToken.children.forEach(function(token, index){
          if(['text', 'code'].indexOf(token.type) > -1){
            ret.push({
              type: env || token.type,
              content: token.content
            });
            env = '';
          }else if(token.type === 'del_open'){
            env = 'deleted';
          }else if(token.type === 'strong_open'){
            env = 'strong';
          }else if(token.type === 'em_open'){
            env = 'em';
          }else if(token.type === 'image'){
            ret.push({
              type: token.type,
              src: token.src
            });
          }
        });
      }

      return ret;
    };

    var getBlockContent = function(blockToken, index){
      if(blockToken.type === 'htmlblock'){
        return getInlineContent(blockToken);
      }else if(blockToken.type === 'heading_open'){
        return {
          type: 'h' + blockToken.hLevel,
          content: getInlineContent(tokens[index+1])
        };
      }else if(blockToken.type === 'paragraph_open'){
        var type = 'p';
        var prefix = '';
        if(env.length){
          prefix = env.join('_') + '_';
        }

        var content = getInlineContent(tokens[index+1]);

        // 处理ol前的数字
        if(env[env.length - 1] === 'li' && env[env.length - 2] === 'ol'){
          content.unshift({
            type:'text',
            content:orderNum[listLevel - 1] + '. '
          });
        }

        return {
          type: prefix + 'p',
          content: content
        };
      }else if(blockToken.type === 'fence'){
        return {
          type: 'code',
          content: blockToken.content
        };
      }else if(blockToken.type === 'code'){
        return {
          type: 'code',
          content: blockToken.content
        };
      }else if(blockToken.type === 'bullet_list_open'){
        env.push('ul');
        listLevel++;
      }else if(blockToken.type === 'ordered_list_open'){
        env.push('ol');
        listLevel++;
      }else if(blockToken.type === 'list_item_open'){
        env.push('li');
        if(env[env.length - 2] === 'ol' ){
          orderNum[listLevel - 1]++;
        }
      }else if(blockToken.type === 'list_item_close'){
        env.pop();
      }else if(blockToken.type === 'bullet_list_close'){
        env.pop();
        listLevel--;
      }else if(blockToken.type === 'ordered_list_close'){
        env.pop();
        listLevel--;
        orderNum[listLevel] = 0;
      }else if(blockToken.type === 'blockquote_open'){
        env.push('blockquote');
      }else if(blockToken.type === 'blockquote_close'){
        env.pop();
      }else if(blockToken.type === 'tr_open'){
        tmp = {
          type: 'table_tr',
          content:[]
        };
        return tmp;
      }else if(blockToken.type === 'th_open'){
        tmp.content.push({
          type: 'table_th',
          content: getInlineContent(tokens[index+1]).map(function(inline){return inline.content;}).join('')
        });
      }else if(blockToken.type === 'td_open'){
        tmp.content.push({
          type: 'table_td',
          content: getInlineContent(tokens[index+1]).map(function(inline){return inline.content;}).join('')
        });
      }
    };

    tokens.forEach(function(token, index){
      var blockContent = getBlockContent(token, index);
      if(!blockContent) return;
      if(!Array.isArray(blockContent)){
        blockContent = [blockContent];
      }
      blockContent.forEach(function(block){
        if(Array.isArray(block.content)){
          block.isArray = true;
        }else{
          block.isArray = false;
        }
        renderList.push(block);
      });
    });

    var obj = {};
    obj[options.name] = ret;

    return renderList;
  }

**Comment by guozimo** [comment]
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
跪求跪求 
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
跪求跪求
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
跪求跪求
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by guozimo** [comment]
跪求跪求
console.log('parser=====',parser)
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
空数组返回 错误的

**Comment by F-loat** [comment]
使用了 typescript 的话，需要在 global.d.ts 中添加以下内容

``` ts
declare namespace JSX {
  interface IntrinsicElements {
    wemark: any
  }
}
```

**Comment by TooBug** [comment]
@F-loat 直接开个PR，加到README中？

**Comment by F-loat** [comment]
@TooBug 已提 PR #80

**Comment by CCZX** [comment]
![(28@YN8Z9(`84E5(5@F) 4C](https://user-images.githubusercontent.com/28856772/72784977-0dda5f80-3c65-11ea-93a2-3306f61f7ead.png)
按照配置弄出来后显示这样是为什么呢？

**Comment by hw18708118867** [comment]
> ![(28@YN8Z9(`84E5(5@F) 4C](https://user-images.githubusercontent.com/28856772/72784977-0dda5f80-3c65-11ea-93a2-3306f61f7ead.png)
> 按照配置弄出来后显示这样是为什么呢？

我也和你相同的问题, 我用的最新的Taro2.0  目前没找到解决方案

**Comment by LoveDongdong** [comment]
taro2.0 以上的需要修改config/index.js里面的配置如图：
![image](https://user-images.githubusercontent.com/26377168/79986215-48f76380-84de-11ea-88ea-fe15efa7e8d2.png)，
因为taro2.0 的编译配置做了调整。详见：http://www.yyyweb.com/5350.html
要在文件开始引入path，要使用绝对路径才能真正忽略掉remarkable.js 的编译。

我也是遇到这个问题困扰了好久，然后发现是配置的原因。

**Comment by TooBug** [comment]
@LoveDongdong 感谢。

**Comment by yxyufo110** [comment]
还是无法正常显示md，
 weapp: {
    compile: {
      exclude: ['src/wemark/remarkable.js'],
    },
  },
