### ISSUE TITLE
有么有具体的小DEMO啊？

### ISSUE THREAD

**Issue by lzq920** [TooBug/wemark#4]
照你的说明弄的，直接就炸了

**Comment by TooBug** [comment]
建议给一下具体的使用代码，看看是什么问题。

**Comment by lzq920** [comment]
好像是引入那个wxml有问题

**Comment by TooBug** [comment]
所以？

**Comment by lzq920** [comment]
所以就炸了。。。你有demo吗？我想参考一下

**Comment by TooBug** [comment]
建议直接上你写的代码，我看看是什么问题。我这边自己在用，也有别人的应用接入了在用，都没问题。

**Comment by lzq920** [comment]
![qq 20170109100021](https://cloud.githubusercontent.com/assets/19420589/21755965/de71fc26-d655-11e6-9c48-6e08dacb263e.png)

**Comment by TooBug** [comment]
看到。应该是readme写错了。获取设备宽度那里，多了一层`device`。README已修正，麻烦再试下。

**Comment by TooBug** [comment]
@lzq920 建议更新一下版本，从master上再下载一次。之前有一个支持video的PR，没做测试，导致heading解析后无法渲染，昨天晚上已经恢复旧版本。
