### ISSUE TITLE
图片放大预览显示

### ISSUE THREAD

**Issue by zyj1609wz** [TooBug/wemark#40]
markdown 显示出来的图片，点击放大查看。
这个功能怎么实现？
谢谢大佬支持

**Comment by TooBug** [comment]
普通的图片`<image>`可以点击放大查看吗？也不能吧。

**Comment by zyj1609wz** [comment]
普通的图片可以放大查看
`//图片预览
 wx.previewImage({
  current: src, // 当前显示图片的http链接
  urls: imgList // 需要预览的图片http链接列表
 })`

**Comment by TooBug** [comment]
可以展示完整的代码吗？普通图片是怎么做的，按理说是完全一样的。

**Comment by zyj1609wz** [comment]
https://github.com/zyj1609wz/imageDemo 

代码已经上传至 GitHub

**Comment by zyj1609wz** [comment]
我已经实现了，之前是我书写错误，导致效果出不来。

感谢。
