### ISSUE TITLE
有序列表内部文字序号问题

### ISSUE THREAD

**Issue by IdanLoo** [TooBug/wemark#43]
原文为：

1. 信息推送

    您在使用我们的服务时，我们可能向您发送电子邮件、短信、资讯或推送通知。您可以按照我们的相关提示，在设备上选择取消订阅。

预期的效果：

```markdown
1. 信息推送

    您在使用我们的服务时，我们可能向您发送电子邮件、短信、资讯或推送通知。您可以按照我们的相关提示，在设备上选择取消订阅。
```

Wemark 实际渲染效果
<img width="377" alt="image" src="https://user-images.githubusercontent.com/22119285/46989899-892f9600-d131-11e8-87f9-b8f2744da5c7.png">

列表内部的文字会莫名其妙多出一个序号。

**Comment by TooBug** [comment]
请问使用的版本是？还有原文markdown用代码发一下？
