### ISSUE TITLE
传入的字符串不是以#开头，会报错

### ISSUE THREAD

**Issue by pluwen** [TooBug/wemark#44]
业务上字符串需要以普通段落开头，会报错

接着发现在字符串前面加上#，就可以正常渲染

希望能改进，支持普通文本开头

插件版本：v2.0.0-beta2

**Comment by TooBug** [comment]
具体报什么错？

**Comment by pluwen** [comment]
![image](https://user-images.githubusercontent.com/555720/47191823-0c442c80-d37c-11e8-891f-3943c045bd2b.png)

![image](https://user-images.githubusercontent.com/555720/47191846-28e06480-d37c-11e8-870c-407c60d5dbd6.png)
数据前面加个 #  就可以用了

**Comment by TooBug** [comment]
试试把`parser.js`第213行

```javascript
if(token.type === 'paragraph_open' && tokens[index-1].type === 'list_item_open'){
	firstInLi = true;
}
```

改成

```javascript
if(token.type === 'paragraph_open' && tokens[index-1] && tokens[index-1].type === 'list_item_open'){
	firstInLi = true;
}
```

看看会不会好。好像是前几天修复一个bug引起的新bug。

**Comment by pluwen** [comment]
非常感谢，可以用了。
