### ISSUE TITLE
type设置为rich-text不能用，没有效果

### ISSUE THREAD

**Issue by cmy0808** [TooBug/wemark#46]
比如：
![image](https://user-images.githubusercontent.com/12969851/47485692-3b253b80-d871-11e8-875d-4de191b4c651.png)
微信小程序中也没有报错，也不出现效果
![image](https://user-images.githubusercontent.com/12969851/47485764-6740bc80-d871-11e8-8bfe-772be502f285.png)

**Comment by TooBug** [comment]
md参数不支持html，如果要使用html，可以直接使用原生rich-text，不需要使用wemark。

另外md参数请在js中声明，在wxml中引用就好，不确定是否可以直接使用文本。

**Comment by cmy0808** [comment]
如果直接使用原生rich-text，无法重置rich-text内的标签样式。因此强烈建议支持html，通过class控制rich-text内的标签样式

**Comment by cmy0808** [comment]
![image](https://user-images.githubusercontent.com/12969851/47900351-8d8cda80-deb7-11e8-9cff-4e37d9dab40d.png)
而且看描述是支持的，但是使用中是没有效果的

**Comment by TooBug** [comment]
1. 原生`rich-text`支持覆盖样式，定好`class`并提供必要的样式即可，wemark也是这么干的，可以查看源码确认
2. 直接渲染html超出了wemark的范围，没有必要，如果要使用请直接使用原生`rich-text`组件

**Comment by TooBug** [comment]
补充下，文档中说的支持`rich-text`渲染是指，可以使用wemark将markdown文本转换成`rich-text`支持的格式，从而渲染出带格式的文本。并不是指支持传入html进行渲染。

**Comment by cmy0808** [comment]
1.原生rich-text支持覆盖样式，2.定好class并提供必要的样式。第二步无法实现，是因为，文章内容是后台编辑生成的，不可能去添加class

**Comment by cmy0808** [comment]
所以希望能有html转为小程序wxml的功能
