### ISSUE TITLE
疑问：我仅仅在json配置文件中加入usingComponents说明后整个页面就全部乱了？

### ISSUE THREAD

**Issue by Heart-King** [TooBug/wemark#48]
我仅仅在json配置文件中加入usingComponents说明：
	"usingComponents": {
		"wemark": "utils/wemark/wemark"
	},	

然后整个页面就没有数据显示了？我都还没有实际加入wemark的控件呢，什么情况

**Comment by TooBug** [comment]
看一下详细的报错信息，要不然无法排查。

**Comment by Heart-King** [comment]
感谢回复，不过应该不是你这个控件的原因，我尝试了一下其余的任何控件，只要一申明 usingComponents ，整个页面就没有任何输出了，非常奇怪，不知道是不是小程序本身的问题。
