### ISSUE TITLE
忽略 meta data

### ISSUE THREAD

**Issue by hyacinthus** [TooBug/wemark#49]
希望能忽略 markdown 前边的 metadata
类似这种：
```
---
layout: post
title: Blogging Like a Hacker
---
```

**Comment by TooBug** [comment]
这个是不是业务中自己处理再丢给wemark就好？貌似它不属于markdown解析的工作。

**Comment by hyacinthus** [comment]
这个英文里更普遍的叫法是 front matter

https://github.com/jxson/front-matter

因为这个库的使用场景应该是直接读取s3这样的对象存储中的md渲染，并不经过后端，
所以引用个库解析一下，或者加个配置开关也是不错的。

还可以考虑智能的用 title 字段当成文章标题，渲染常见的时间，来源，作者等字段。。。

当然选择不解析也没什么问题。关掉这个issue就好。

**Comment by imaiya** [comment]
这个确实是有一部分需求的,我也遇到了,不过我自己在后台处理了一下
