### ISSUE TITLE
块级代码高亮没效果

### ISSUE THREAD

**Issue by imaiya** [TooBug/wemark#51]
感谢作者的库,遇到一个问题:
```
代码
```
这样格式的代码没有高亮,highlight有没有都没有区别

**Comment by TooBug** [comment]
没看懂……代码高亮应该需要指定语言，没有做自动探测语言的。

**Comment by imaiya** [comment]
确实是没有指定语言的问题.
但是现在很多人写markdown也是不指定语言的,是否可以考虑支持代码块语言的自动探测或者在组件上增加一个属性,传入当前md中代码块的语言类别呢,因为一篇文档一般只会有一种代码语言
