### ISSUE TITLE
请问您说的放到根目录下， 是跟src同级的目录吗？ 

### ISSUE THREAD

**Issue by RangerWolf** [TooBug/wemark#55]
![image](https://user-images.githubusercontent.com/3512774/51177048-8d6a7b80-18f9-11e9-8347-5c939e4dd4d7.png)

我是从 https://github.com/F-loat/mpvue-quickstart  这个项目开始做起来的  
对前端的东西刚接触， 不太熟悉，谢谢！

**Comment by TooBug** [comment]
再看一下README？并没有说放到根目录下，是放到static目录下。
