### ISSUE TITLE
readme显示异常

### ISSUE THREAD

**Issue by huangjianke** [TooBug/wemark#56]
请问下，这种情况有解决方案么

<img width="320" alt="wechatimg8 1" src="https://user-images.githubusercontent.com/8692455/51223030-28576a00-197b-11e9-9017-a76699292c99.png">

**Comment by TooBug** [comment]
有详细一点的说明吗？按理说不会不见的，这个是小程序的基础功能，应该不至于这么弱智。（当然，我也没有测其它的模式。）
