### ISSUE TITLE
代码块片段好像不支持 ``符号，被解析为[object]

### ISSUE THREAD

**Issue by giscafer** [TooBug/wemark#58]
![wemark](https://user-images.githubusercontent.com/8676711/53140026-68d38480-35c6-11e9-8144-c94c86810529.png)

 ```js 
  const arrayToHtmlList = (arr, listID) =>
  (el => (
    (el = document.querySelector('#' + listID)),
    (el.innerHTML += arr.map(item => `<li>${item}</li>`).join(''))
  ))(); 
 ```

**Comment by TooBug** [comment]
收到，晚点检查一下具体原因。

**Comment by TooBug** [comment]
已处理。关闭高亮时的表现待验证。

**Comment by Songkeys** [comment]
@TooBug 
我之前提了这个 PR （https://github.com/TooBug/wemark/pull/39）。
后期发现代码块如果包含 html 或者 markdown 时，会被转换成这一类嵌套的 token，也没找到合适的原生办法关闭，所以暂时用 flattenToken 这个丑陋的办法代替。
（这次的 commit 在代码量较多时可能会影响性能？也可能影响不大。总之如果有原生办法直接关掉这种嵌套就好了。）

**Comment by TooBug** [comment]
@Songkeys 不止html或者markdown，这个issue反馈的js中的模板字符串是同一类问题。prism.js对某些情况就是会产生嵌套。这个`flattenToken`我也保留了，暂时想不出更好的办法。
