### ISSUE TITLE
提几个遇到的小问题

### ISSUE THREAD

**Issue by pjialin** [TooBug/wemark#6]
首先非常感谢作者的无私奉献，使用中的小程序已上线，再次感谢！

> 有几点问题

- 纯文本需有两个换行符才会换行
比如源码是这样
```
test1
test2
``` 
渲染出来是这样
```
test1test2
```
- 还有就是现在没做删除线是吗，没有效果

**Comment by TooBug** [comment]
第一个问题，markdown中文本没有换行一说，只有另起一段。段与段之间就是靠两个换行符分隔的。

第二个问题，确实没支持删除线，需要的话可以考虑加上。

**Comment by TooBug** [comment]
删除线已在1.1.0中添加。
