### ISSUE TITLE
能渲染字符串html吗  我是taro

### ISSUE THREAD

**Issue by zhangfan6644777** [TooBug/wemark#60]

**Comment by TooBug** [comment]
具体一点？

如果是指html富文本的话，不支持。可以看看其他的库。

**Comment by zhangfan6644777** [comment]
> 具体一点？
> 
> 如果是指html富文本的话，不支持。可以看看其他的库。

就是渲染'<div>11111</div>' 这种 不过我解决了  用的是把wxParse 封装成taro组件

**Comment by TooBug** [comment]
嗯。HTML不支持，wemark只处理markdown的渲染。
