### ISSUE TITLE
markdown 解析错误

### ISSUE THREAD

**Issue by ANDEMEN** [TooBug/wemark#65]
当遇到给 * 加粗时，使用 `*****` 不会渲染成加粗的 * 而直接是 *****，使用 `__*__` 则没有问题。

**Comment by TooBug** [comment]
*****

**\***

**Comment by TooBug** [comment]
可以看上面一条回复。`*****`可能就是不规范的markdown写法，Github也无法解析。如果要使用`*`作为正文字符，需要对它转义。这样写就好了`**\***`。
