### ISSUE TITLE
使用taro 版本支持百度小程序引入不了项目 项目看不了

### ISSUE THREAD

**Issue by guozimo** [TooBug/wemark#66]
使用taro 版本支持百度小程序引入不了项目 项目看不了
希望官方可以给解决办法 谢谢了 微信gwd1991 微信群有很多这样的开发者 我们需要一个完整的生态 谢谢 加我一下详细说明一下问题 紧急 希望理解

**Comment by TooBug** [comment]
请详细反馈具体问题以便排查。wemark唯一反馈问题的方式是Github issue。不提供其他方式，微信也不加陌生人，见谅。

另外wemark标题中写得比较清楚，是针对微信小程序。

如果是百度小程序的问题目前没有精力支持，欢迎提供技术细节或者Pull Request。至于完整生态的问题超出了wemark或者作者/维护者的考虑范围，欢迎大家一起来完善。

**Comment by guozimo** [comment]
tokens 为kong

**Comment by guozimo** [comment]
29
789 125 TooBug/wemark
 Code  Issues 8  Pull requests 0  Insights
var tokens = parser.parse(md, {}); console.log('进入函数mdtokens====',tokens) 这个输出的tokens 是一个空数组是怎么回事啊 #67

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {}); console.log('进入函数mdtokens====',tokens) 这个输出的tokens 是一个空数组是怎么回事啊

**Comment by Songkeys** [comment]
请仔细查看 Taro 文档：<https://nervjs.github.io/taro/docs/mini-third-party.html>

**但是值得注意的是，如果在 Taro 项目引用了小程序原生的第三方组件和插件，那么该项目将不再具备多端转换的能力，例如，如果使用了微信小程序的第三方组件，那么项目只能转换成微信小程序，转义成其他平台会失效，使用其他小程序原生组件同理。**
