### ISSUE TITLE
 var tokens = parser.parse(md, {}); console.log('进入函数mdtokens====',tokens) 这个输出的tokens 是一个空数组是怎么回事啊

### ISSUE THREAD

**Issue by guozimo** [TooBug/wemark#67]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by guozimo** [comment]
var tokens = parser.parse(md, {});
console.log('进入函数mdtokens====',tokens)
这个输出的tokens 是一个空数组是怎么回事啊
为什么输出的是一个空的数组的传递的md 是'## hello, world'
单数打印出来的toknes 是一个空数组
taro 版本使用 跪求

**Comment by Songkeys** [comment]
你是把 GitHub 的 issue 区当贴吧灌水了吗？

我 watch 了这个项目，刚刚早上起来一看邮箱里多了四十多封未读，全部来自于你。

遇到问题心急可以理解，但首先也请尊重项目作者和贡献者。发 issue 时完整阐明自己的问题，以及你做了哪些调查，而不是在这里用这种语气重复发大量相同内容，还让人加你微信……

多余的话不说了……请看[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)。

**Comment by guozimo** [comment]
就回家

**Comment by guozimo** [comment]
你妈妈

**Comment by guozimo** [comment]
关闭
