### ISSUE TITLE
真机渲染某些 Markdown 的时候出现 SyntaxError Unexpect EOF 错误

### ISSUE THREAD

**Issue by lzwjava** [TooBug/wemark#7]
比如渲染下面这个文本的时候：

```
## 感谢大家，上期629人参与了

## 这次直播大纲

今晚再开一期。讲讲最近学到的：

1. 用户登录，微信要求过程非常安全，分为明文数据和敏感数据，这一部分搞了半天，比较难懂，讲讲
2. 本地存储，微信本地存储的 API
3. 直播技术，如何在小程序弄直播

![login1.png](http://i.quzhiboapp.com/AJ0B8j)


# 最近的进展

## 报名页面

![small2.jpeg ](http://i.quzhiboapp.com/5K1dzP)

## 小程序里看直播

![smallapp.jpeg](http://i.quzhiboapp.com/wEMOst)

# 上期直播情况

![xi1.jpeg](http://i.quzhiboapp.com/pXgJXq)

![xi2.jpeg](http://i.quzhiboapp.com/1RKHm1)

![xi5.jpeg](http://i.quzhiboapp.com/FvxJKC)

![xi6.jpeg](http://i.quzhiboapp.com/vJ5BS3)


```

真机上出现错误：

![wechatimg3951](https://cloud.githubusercontent.com/assets/5022872/22078874/99795636-ddf4-11e6-98b5-5a782177fa86.jpg)

虽然 Markdown 能显示，但这会导致页面的其它 JS 执行失败。比如其它不相关的元素显示不了。

求教~~

@TooBug

**Comment by TooBug** [comment]
有试过屏蔽页面其它部分吗？确定是remark导致的？

**Comment by TooBug** [comment]
查了一点，这个会不会是其它地方JSON解析的问题？

**Comment by lzwjava** [comment]
确实，应该是其他地方 json 的问题。wx.request 之后解析不对的问题，我再看看吧。感谢回复哈。

**Comment by lzwjava** [comment]
![image](https://cloud.githubusercontent.com/assets/5022872/22145043/b8fd7e14-df3a-11e6-8e1c-1c7a33c0964c.png)

找到问题了，把文本粘贴到 [JSBIN](http://jsbin.com/mubameporu/edit?html,output) 上发现有个小红点，不可见字符，去掉就行了。调试正常，微信浏览器真机会出现错误~~

http://stackoverflow.com/questions/12719859/no-visible-cause-for-unexpected-token-illegal

还是感谢作者~~错过 Wemark 了哈。Wemark 很赞，👍 ~~

**Comment by TooBug** [comment]
这个问题还挺诡异，回头我也研究一下。


解决问题就好。
