### ISSUE TITLE
好像有错误

### ISSUE THREAD

**Issue by ourfor** [TooBug/wemark#74]
<img width="1572" alt="Xnip2019-04-24_21-47-43" src="https://user-images.githubusercontent.com/33711476/56664488-c7a69e80-66da-11e9-937c-56f53583cc59.png">

**Comment by TooBug** [comment]
麻烦说明具体的使用方式，要不然无法解答任何疑问。

截图来看你好像在使用本库的taro demo，可以仔细看一下README的说明，需要复制wemark库。或者也可以参考 #36 。

**Comment by ourfor** [comment]
感谢答复，我再看看

**Comment by ourfor** [comment]
解决了，原来后面这wemark是文件名，刚入门小程序，打扰了😂
