### ISSUE TITLE
MD中会出现  ![](/images/xxxx.png) 

### ISSUE THREAD

**Issue by xiyouMc** [TooBug/wemark#8]
目前的版本不支持渲染这样的Image . 所以 是否可以在parse方法中，传入 仓库地址，然后 找到对应的Image呢？

**Comment by TooBug** [comment]
传入仓库地址是什么概念？这个路径确实会找不到图片呀。

**Comment by xiyouMc** [comment]
比如说 xiyouMc/WebHubBot 这个项目下的Readme里面包含一个仓库的图片 ![](/images/Bot.png)。
那么这样的路径在wemark里面找不到的。  所以 是否可以 传入  https://github.com/xiyouMc/WebHubBot、  然后 wemark内部拼装 为  https://github.com/xiyouMc/WebHubBot/images/Bot.png。  或者只需要传入 xiyouMc/WebHubBot 这个路径。

**Comment by TooBug** [comment]
这个超出了markdown解析库的职责了，建议在渲染前自行进行预处理，简单替换一下即可。


另外你给的这个地址也是无法访问到图片的，github的图片需要点raw获取原图地址才可以访问。

**Comment by xiyouMc** [comment]
这个链接是 测试链接。  Github 中 Image 标签，也可以指定仓库位置的。 不用raw原路径的。

**Comment by TooBug** [comment]
你可以自己看一下Github中解析出来的图片url地址，就是用的raw。另外补充说明一下，Markdown并不只是Github在用，虽然Github对图片地址做了处理，但你不可能要求每一个处理Markdown的软件都对Github做特殊处理，这个超出了解析库的职责。

**Comment by xiyouMc** [comment]
谢了。 你的理解能力有待提升。

**Comment by TooBug** [comment]
1. 有问题请详细描述，自己没有描述清楚，我尝试猜了三次，好累
2. 已经告诉你加域名这件事情不属于解析库干的事，Github也没自动给你加域名。能显示是因为MD文件和图片都在Github上，用的相对路径。要不然你在只有.md文件没有图片的情况下换个软件打开试试看能不能显示？
3. 也告诉你了，Github不止是直接显示了相对路径，在路径中加了raw的。你要是有不同意见，拿demo来看，给我一个404的网址<https://github.com/xiyouMc/WebHubBot/images/Bot.png>，我也不知道你想说什么

最后，用了开源库不说一句感谢我也不说啥了。我还在这费心费力地陪你解决问题，结果你连一个完整的问题描述都没有，到头来你还说是我理解能力有问题，要是再这么说一句就别怪我开骂了。

**Comment by xiyouMc** [comment]
多学学人家wxparse

**Comment by TooBug** [comment]
开源软件的世界很自由，爱来来，爱走走，你喜欢wxparse去喜欢就是了，我就是看它有问题才自己写。

之前打过招呼了，说话不要阴阳怪气。

有多远滚多远。
