### ISSUE TITLE
不支持嵌套

### ISSUE THREAD

**Issue by southpush** [TooBug/wemark#82]
测试了一下随便复制了一段markdown文本，发现区块嵌套完全没有显示。后边再测试多几种，发现好像嵌套的都没办法显示
下面这个是测试的
> 区块1
>>区块2
> + 列表

放到小程序里这样的，嵌套的都没有渲染出来
![image](https://user-images.githubusercontent.com/33292427/63919240-f1007e00-ca70-11e9-8c5a-cc222da55611.png)

不清楚这个是bug还是wemark并不支持嵌套

**Comment by TooBug** [comment]
因为小程序的能力有限制，理论上无法实现无限嵌套。如果要写死嵌套N层，那么模板中需要写死N层，这个会导致模板体积爆炸，同时随着模板体积增大，性能会快速下降。

所以，合理的回复是：这个功能可以做，但是wemark没有去做。如果有这方面的需求，可以自己改一下，有多少层嵌套就要加多少层嵌套的模板，具体可以参考wxparse以及remax等项目。

**Comment by southpush** [comment]
好的，我去叫写文章的人别搞多层嵌套，问题解决了
