### ISSUE TITLE
如何给文字添加背景颜色和文字颜色，table和font好像都不支持？

### ISSUE THREAD

**Issue by majianwen** [TooBug/wemark#92]
<table><tr><td bgcolor=#7FFFD4>文字内容</td></tr><td bgcolor=#ffFD4>文字内容</td><td bgcolor=#379809>文字内容</td><td bgcolor=#hiu809>文字内容</td></tr></table>

**Comment by TooBug** [comment]
这是markdown解析，markdown本身不支持这样的特性。
