### ISSUE TITLE
图片如何设置宽度呢？

### ISSUE THREAD

**Issue by crestin** [TooBug/wemark#97]
`![示例图](http://xxx/img.png)`
如题，谢谢！

还有就是，详细的文档，比如图片都能设置些什么？去哪里查看呢？

**Comment by TooBug** [comment]
Markdown是不可以对图片设置样式的。

**Comment by TooBug** [comment]
多补一条：如果要设置，需要修改CSS，统一设置图片的样式。具体可设置的样式参见小程序文档。
